# Generated by Django 5.2.3 on 2025-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
